# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGIXLUGL21a2cvpxxFudxpecrWD0re0D
"""

# ============================================================
# Gemini Functions
# ============================================================

# 建立 Gemini API Client 的函式
def make_gemini_client():

    # 如果 google-genai 套件沒有安裝
    # GEMINI_INSTALLED 通常是一個布林值
    # False 代表套件不存在
    if not GEMINI_INSTALLED:

        # 顯示沒安裝好的提示訊息
        print("google-genai is not installed. Using local fallback content.")

        # 回傳 None，代表無法使用 Gemini
        return None

    # 從環境變數讀取 API KEY
    # os.getenv() 可以安全取得環境變數
    api_key = os.getenv("GEMINI_API_KEY")

    # 如果沒有設定 API KEY
    if not api_key:

        # 顯示沒安裝好的提示訊息
        print("GEMINI_API_KEY is not set. Using local fallback content.")

        # 回傳 None，之後程式會改用本地 fallback 內容
        return None

    # 嘗試建立 Gemini Client
    try:

        # 成功讀取 API KEY
        print("GEMINI_API_KEY loaded successfully.")

        # 建立 Gemini Client 物件並回傳
        return genai.Client(api_key=api_key)

    # 如果建立失敗
    except Exception as e:

        # 顯示錯誤訊息
        print("Gemini client failed. Using local fallback content.")

        # 印出詳細錯誤
        print("Error:", e)

        # 回傳 None
        return None


# 使用 Gemini 生成內容，並支援 Retry 機制
def gemini_generate_with_retry(
    client,
    prompt,
    response_json=True,
    max_retries=3,
    temperature=0.35
):

    # 如果 client 是 None
    # 代表 Gemini 無法使用
    if client is None:
        return None

    # 紀錄最後一次錯誤
    last_error = None

    # 記錄已使用過的模型
    # 避免重複使用
    used_models = []

    # 逐一嘗試 fallback 模型
    for model in GEMINI_FALLBACK_MODELS:

        # 如果模型已經用過
        if model in used_models:
            continue

        # 加入已使用清單
        used_models.append(model)

        # Retry 機制
        # 每個模型最多重試 max_retries 次
        for attempt in range(max_retries):

            try:

                # Gemini 生成設定
                config_kwargs = {
                    "temperature": temperature
                }

                # 如果希望 Gemini 回傳 JSON
                if response_json:

                    # 指定 MIME TYPE 為 JSON
                    config_kwargs["response_mime_type"] = "application/json"

                # 呼叫 Gemini API
                response = client.models.generate_content(

                    # 指定模型名稱
                    model=model,

                    # 傳入 Prompt
                    contents=prompt,

                    # 建立設定物件
                    config=types.GenerateContentConfig(**config_kwargs),
                )

                # 如果 Gemini 有回傳文字
                if response.text and response.text.strip():

                    # 去除前後空白後回傳
                    return response.text.strip()

                # 如果回傳空字串
                last_error = RuntimeError("Gemini returned empty text.")

            # API 呼叫失敗
            except Exception as e:

                # 記錄最後錯誤
                last_error = e

                # 轉成字串方便判斷
                error_text = str(e)

                # 判斷是否屬於可重試錯誤
                retryable = (

                    # 503 = 服務暫時不可用
                    "503" in error_text

                    # UNAVAILABLE = 服務不可用
                    or "UNAVAILABLE" in error_text

                    # 429 = rate limit
                    or "429" in error_text

                    # 資源耗盡
                    or "RESOURCE_EXHAUSTED" in error_text

                    # 高流量
                    or "high demand" in error_text.lower()
                )

                # 如果是可重試錯誤
                if retryable:

                    # 計算等待時間
                    # attempt 越高等待越久
                    wait_time = 2 + attempt * 3 + random.random()

                    # 顯示提示訊息
                    print(
                        f"Gemini is busy or rate-limited. "
                        f"Retry in {wait_time:.1f} seconds..."
                    )

                    # 暫停一段時間
                    time.sleep(wait_time)

                    # 繼續 retry
                    continue

                # 非可重試錯誤
                print(f"Gemini model {model} failed:", e)

                # 跳出 retry loop
                break

        # 當前模型失敗後
        # 嘗試下一個模型
        print("Trying next Gemini model if available...")

    # 所有模型都失敗
    print("Gemini failed after retries. Last error:", last_error)

    return None


# ============================================================
# Resume Content Generation
# ============================================================

# 建立本地 fallback 履歷內容
# 當 Gemini 無法使用時會改用這個
def build_fallback_resume_content(raw):

    # 將技能字串切割成 list
    skills = split_comma_text(raw["skills"])

    # 將證照切割成 list
    certificates = split_comma_text(raw["certificates"])

    # 將比賽經歷切割成 list
    competitions = split_comma_text(raw["competitions"])

    # 如果沒有 skills
    # 但有 specialty
    if not skills and raw["specialty"]:

        # 將 specialty 當作 skill
        skills = [raw["specialty"]]

    # 如果沒有證照
    if not certificates:

        # 填入預設值
        certificates = ["None"]

    # 如果沒有競賽
    if not competitions:

        # 填入預設值
        competitions = ["None"]

    # 建立自我介紹 summary
    summary = (

        # 使用 f-string 插入使用者資料
        f"My name is {raw['name']}. "

        f"I am currently studying at {raw['school']}, "
        f"majoring in {raw['major']}. "

        f"I am interested in applying for "
        f"{raw['target_position']}-related positions "
        f"in {raw['target_location']}. "

        f"My expected monthly salary is "
        f"{raw['expected_monthly_salary']}. "

        f"My main specialty is {raw['specialty']}. "

        # 固定內容
        "Through academic learning, "
        "project participation, and practical training, "

        "I have developed analytical thinking, "
        "communication ability, teamwork, "
        "and a strong willingness to keep learning. "
    )

    # 如果有工作經驗
    if raw["experience"]:

        # 加入 summary
        summary += (
            f"My previous work or internship "
            f"experience includes {raw['experience']}. "
        )

    # 加入結尾
    summary += (
        "I hope to apply my background and strengths "
        "in a real workplace, learn from experienced "
        "professionals, and gradually develop into a "
        "reliable and responsible team member."
    )

    # 回傳完整履歷資料
    return {

        # 姓名
        "name": raw["name"],

        # 目標職位
        "target_position": raw["target_position"],

        # 履歷標題
        "headline": f"{raw['target_position']} Candidate",

        # 求職偏好
        "job_preferences": {

            # 目標職位
            "target_position": raw["target_position"],

            # 工作地點
            "target_location": raw["target_location"],

            # 期望薪資
            "expected_monthly_salary":
                raw["expected_monthly_salary"],
        },

        # 聯絡資訊
        "contact": {

            # 地址
            "address": raw["address"],

            # Email
            "email": raw["email"],

            # 電話
            "phone": raw["phone"],
        },

        # 自我介紹
        "profile_summary": summary,

        # 專長
        "specialty": raw["specialty"],

        # 技能列表
        "skills": skills,

        # 教育背景
        "education": [
            {
                "school": raw["school"],
                "major": raw["major"],

                # 教育描述
                "description":
                    "Academic background related to "
                    "the candidate's professional development.",
            }
        ],

        # 證照
        "certificates": certificates,

        # 競賽
        "competitions": competitions,

        # 工作經驗
        "experience": [
            {
                "title": "Work / Internship Experience",

                "description":
                    raw["experience"]
                    if raw["experience"]
                    else
                    "No formal work or internship experience provided.",
            }
        ],

        # 個人優勢
        "strengths": [
            "Willingness to learn",
            "Communication ability",
            "Teamwork",
            "Analytical thinking",
            "Adaptability",
        ],

        # 職涯目標
        "career_objective": (
            f"To apply for {raw['target_position']}-related "
            f"positions in {raw['target_location']}, "

            f"with an expected monthly salary of "
            f"{raw['expected_monthly_salary']}, "

            "while gaining practical workplace experience "
            "and continuing to improve professional skills."
        ),
    }

